# Generated by Django 5.2 on 2025-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gigs',
            table='gigs',
        ),
        migrations.AlterModelTable(
            name='services',
            table='services',
        ),
    ]
