# Generated by Django 5.2 on 2025-05-30 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_gigs_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_gigs', to=settings.AUTH_USER_MODEL),
        ),
    ]
